<a href="https://colab.research.google.com/github/Shreshth-112/100_Days_of_Machine_Learning/blob/main/day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd

In [24]:
df = pd.read_csv('customer.csv')

In [25]:
df.sample(5)

age  gender   review education purchased
27   69  Female     Poor        PG        No
33   89  Female     Good        PG       Yes
0    30  Female  Average    School        No
30   73    Male  Average        UG        No
11   74    Male     Good        UG       Yes

In [26]:
df = df.iloc[:,2:]

In [27]:
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],
                                                 test_size = 0.2)

In [29]:
X_train

review education
37  Average        PG
35     Poor    School
14     Poor        PG
7      Poor    School
48     Good        UG
38     Good    School
29  Average        UG
1      Poor        UG
27     Poor        PG
30  Average        UG
0   Average    School
18     Good    School
16     Poor        UG
32  Average        UG
15     Poor        UG
19     Poor        PG
25     Good    School
21  Average        PG
9      Good        UG
31     Poor    School
24  Average        PG
5   Average    School
23     Good    School
46     Poor        PG
4   Average        UG
34  Average    School
2      Good        PG
42     Good        PG
49     Good        UG
22     Poor        PG
26     Poor        PG
39     Poor        PG
12     Poor    School
43     Poor        PG
47     Good        PG
33     Good        PG
17     Poor        UG
36     Good        UG
6      Good    School
10     Good        UG

In [30]:
from sklearn.preprocessing import OrdinalEncoder

In [31]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [32]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [33]:
X_train = oe.transform(X_train)

In [34]:
X_train

array([[1., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [2., 1.]])

In [35]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [36]:
X_train

array([[1., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 1.],
       [0., 0.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [2., 1.]])

In [37]:
from sklearn.preprocessing import LabelEncoder

In [38]:
le = LabelEncoder()

In [39]:
le.fit(y_train)

LabelEncoder()

In [40]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [41]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [42]:
y_train

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1])